# Image from https://hub.docker.com (syntax: repo/image:version)
ARG BASE_CONTAINER=jupyter/minimal-notebook
FROM $BASE_CONTAINER

# Person responsible
MAINTAINER helge.dzierzon@brockmann-consult.de

LABEL name=xcube
LABEL version=0.3.0.dev1
LABEL conda_env=xcube


USER root

# Install all OS dependencies for fully functional notebook server
#RUN apt-get update && apt-get clean && rm -rf /var/lib/apt/lists/*
#RUN apt-get update && \
#    apt-get install -y --no-install-recommends git && \
#    rm -rf /var/lib/apt/lists/*

USER $NB_UID

# Update conda and install dependencies specified in environment.yml
# Install eodag
RUN git clone https://github.com/dcs4cop/xcube && \
    cd /home/$NB_USER/xcube && \
    conda env create -f=environment.yml
#    conda clean --all -f -y && \
#    fix-permissions $CONDA_DIR && \
#    fix-permissions /home/$NB_USER

# Switch back to jovyan to avoid accidental container runs as root
USER $NB_UID


# Ensure usage of bash (simplifies source activate calls)
SHELL ["/bin/bash", "-c"]

WORKDIR /xcube

# Setup xcube_server package
RUN cd /home/$NB_USER/xcube && \
    source activate xcube && \
    python setup.py develop

# Test xcube package
ENV NUMBA_DISABLE_JIT 1
#RUN source activate xcube && pytest

# Export web server port 8000
EXPOSE 8000

# Start server
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["source activate xcube && xcube"]